[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
rustflags = ["-C", "link-arg=-Wl,--allow-multiple-definition"]

[target.x86_64-pc-windows-msvc]
rustflags = ["/FORCE:MULTIPLE"]

[profile.release]
opt-level = 3
lto = true
